# **Phase 2: Predictive Modeling**

### **[1] Objectve:**
Predict the probability of customer churn using historical customer data, so that high-risk customers can be identified for retention efforts.

### **[2] Decide WHAT Features are allowed:**
A feature is only allowed if it is known *before* the customer churns.

- Features Allowed:
  - Time--------------------> tenure
  - Price--------------------> MonthlyCharges, TotalCharges
  - Commitment-----------> Contract
  - Payment behavior------> PaymentMethod, PaperlessBilling
  - Services-----------------> InternetService, Add-ons
  - Demographics (weak)--> SeniorCitizen, Partner, Dependents

- Features NOT Allowed:
  - Anything using churn label
  - Post-churn information
  - Heuristic LTVs

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [4]:
# convert datatype of 'TotalCharges' into integer

df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df = df.dropna()

In [5]:
# Look for all the "NaN" values in TotalCharges
print(df[df['TotalCharges'].isna()])

Empty DataFrame
Columns: [customerID, gender, SeniorCitizen, Partner, Dependents, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges, Churn]
Index: []

[0 rows x 21 columns]

In [6]:
# Tenure Transformation (Customer Age)
df['tenure_years'] = df['tenure'] / 12

In [7]:
# Price Intensity
df['charge_per_tenure'] = df['MonthlyCharges'] / (df['tenure'] + 1)

In [8]:
# Contract Commitment Score
df['contract_commitment'] = df['Contract'].map({
    'Month-to-month': 0,
    'One year': 1,
    'Two year': 2
})

df = df.drop(columns=['Contract'])

In [9]:
# Auto-Pay Indicator
df['auto_pay'] = df['PaymentMethod'].map({
    'Electronic check': 0,
    'Mailed check': 0,
    'Bank transfer (automatic)': 1,
    'Credit card (automatic)': 1
})

df = df.drop(columns=['PaymentMethod'])

In [10]:
# Early Life Risk Indicator
df['is_new_customer'] = (df['tenure'] <= 12).astype(int)

In [11]:
# Service Count
service_cols = [
    'OnlineSecurity',
    'OnlineBackup',
    'DeviceProtection',
    'TechSupport',
    'StreamingTV',
    'StreamingMovies'
]

df['service_count'] = df[service_cols].apply(lambda x: (x == 'Yes').sum(), axis=1)

In [12]:
# Fibre risk Indicator
df['is_fiber'] = (df['InternetService'] == 'Fiber optic').astype(int)

In [13]:
# Features Sanity Check

features_to_check = [
    'tenure_years',
    'charge_per_tenure',
    'contract_commitment',
    'auto_pay',
    'service_count',
    'is_new_customer'
]

df[features_to_check].describe()

,tenure_years,charge_per_tenure,contract_commitment,auto_pay,service_count,is_new_customer
count,7032.000000,7032.000000,7032.000000,7032.000000,7032.000000,7032.000000
mean,2.701816,5.714882,0.688567,0.435580,2.038111,0.309300
std,2.045438,8.567435,0.832934,0.495868,1.847161,0.462238
min,0.083333,0.264384,0.000000,0.000000,0.000000,0.000000
25%,0.750000,1.250000,0.000000,0.000000,0.000000,0.000000
50%,2.416667,2.073598,0.000000,0.000000,2.000000,0.000000
75%,4.583333,5.884842,1.000000,1.000000,3.000000,1.000000
max,6.000000,51.225000,2.000000,1.000000,6.000000,1.000000

**Feature Validation Summary**

- A minimal feature set (7 variables) selected to balance predictive signal and interpretability.
- Features represent customer lifecycle, pricing pressure, contractual commitment, engagement depth, and known high-risk segments.
- Redundant categorical expansions were intentionally excluded to reduce noise and overfitting.

In [14]:
selected_features = [
    'tenure_years',
    'charge_per_tenure',
    'contract_commitment',
    'auto_pay',
    'service_count',
    'is_fiber',
    'is_new_customer'
]

X = df[selected_features]
y = (df['Churn'] == 'Yes').astype(int)

In [15]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    max_iter=1000,
    solver='liblinear'
)

model.fit(X, y)

LogisticRegression(max_iter=1000, solver='liblinear')

In [16]:
coef_table = (
    pd.DataFrame({
        'Feature': X.columns,
        'Coefficient': model.coef_[0]
    })
    .sort_values(by='Coefficient', ascending=False)
)

coef_table

               Feature  Coefficient
5             is_fiber     1.158772
6      is_new_customer     0.107044
4        service_count     0.100211
1    charge_per_tenure     0.048467
0         tenure_years    -0.162628
3             auto_pay    -0.266524
2  contract_commitment    -1.035892

### **[8]Prioritization Table (SIZE x RISK x VALUE)**

In [22]:
# Create segments

df['priority_segment'] = np.select(
    [
        (df['is_fiber'] == 1) & (df['contract_commitment'] == 0),
        (df['is_fiber'] == 1) & (df['is_new_customer'] == 1),
        (df['is_fiber'] == 1) & (df['contract_commitment'] > 0),
        (df['is_fiber'] == 0) & (df['is_new_customer'] == 1),
        (df['is_fiber'] == 0) & (df['contract_commitment'] == 0) & (df['tenure_years'] > 1),
    ],
    [
        'Fiber + Month-to-Month',
        'Fiber + New',
        'Fiber + Contract',
        'New Non-Fiber',
        'Month-to-Month (Tenured)'
    ],
    default='Stable / Low Risk'
)

In [23]:
# Size x Risk x Value

priority_table = (
    df
    .groupby('priority_segment')
    .agg(
        Customers=('customerID', 'count'),
        ChurnRate=('Churn', lambda x: (x == 'Yes').mean()),
        AvgMonthlyRevenue=('MonthlyCharges', 'mean')
    )
    .reset_index()
)

In [24]:
# Priority Score

priority_table['PriorityScore'] = (
    priority_table['Customers'] *
    priority_table['ChurnRate'] *
    priority_table['AvgMonthlyRevenue']
)

priority_table = priority_table.sort_values(
    by='PriorityScore',
    ascending=False
)

priority_table

,priority_segment,Customers,ChurnRate,AvgMonthlyRevenue,PriorityScore
1,Fiber + Month-to-Month,2128,0.546053,87.021194,101118.626974
4,New Non-Fiber,1252,0.313099,37.001358,14504.532268
0,Fiber + Contract,961,0.138398,101.392300,13485.175858
3,Month-to-Month (Tenured),669,0.167414,46.651271,5224.942302
5,Stable / Low Risk,2015,0.033747,47.067593,3200.596328
2,Fiber + New,7,0.285714,95.042857,190.085714

In [25]:
# Top 10%

priority_table['PriorityPct'] = (
    priority_table['PriorityScore'] /
    priority_table['PriorityScore'].sum()
)

priority_table

,priority_segment,Customers,ChurnRate,AvgMonthlyRevenue,PriorityScore,PriorityPct
1,Fiber + Month-to-Month,2128,0.546053,87.021194,101118.626974,0.734212
4,New Non-Fiber,1252,0.313099,37.001358,14504.532268,0.105316
0,Fiber + Contract,961,0.138398,101.392300,13485.175858,0.097915
3,Month-to-Month (Tenured),669,0.167414,46.651271,5224.942302,0.037938
5,Stable / Low Risk,2015,0.033747,47.067593,3200.596328,0.023239
2,Fiber + New,7,0.285714,95.042857,190.085714,0.001380

### **Immediately prioritize retention actions for Fiber + Month-to-Month customers.**

>**Fiber + Month-to-Month**
- Customers: 2,128
- Churn Rate: 54.6% (catastrophic)
- Avg Monthly Revenue: ₹87
- Priority Contribution: 73.4% of total churn value

*This single segment explains ~¾ of the problem.*

>**All other segments**

Segment --> Priority % -->Reality check

New Non-Fiber --> 10.5% --> Worth watching, not urgent

Fiber + Contract --> 9.8% --> High value but already protected

Month-to-Month (Tenured) --> 3.8% --> Low churn leverage

Stable / Low Risk --> 2.3% --> Do nothing

Fiber + New --> 0.1% --> Statistically irrelevant

>**Recommended Action**

**Target only the top ~20–25% of Fiber + Month-to-Month customers, ranked by churn probability × revenue.**

Actions:
- Push 12-month contract upgrade with incentive
- Bundle auto-pay enrollment
- Avoid blanket discounts — precision only

***Retaining even 10–15% of this segment protects a disproportionate share of revenue, since this group alone contributes over 70% of churn risk value.***

In [44]:
from sklearn.model_selection import train_test_split

X_train, X_temp, y_train, y_temp = train_test_split(
    X, y,
    test_size=0.30,
    stratify=y,
    random_state=42
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp,
    test_size=0.50,
    stratify=y_temp,
    random_state=42
)

In [45]:
from sklearn.linear_model import LogisticRegression

log_model = LogisticRegression(
    max_iter=1000,
    class_weight='balanced'
)

log_model.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [46]:
from sklearn.metrics import roc_auc_score, precision_recall_curve, auc

# ROC-AUC
roc_auc_log = roc_auc_score(
    y_test,
    log_model.predict_proba(X_test)[:, 1]
)

# PR-AUC
precision, recall, _ = precision_recall_curve(
    y_test,
    log_model.predict_proba(X_test)[:, 1]
)
pr_auc_log = auc(recall, precision)

roc_auc_log, pr_auc_log

(0.8183963133640553, 0.6133755310449286)

In [47]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    n_estimators=300,
    max_depth=4,
    learning_rate=0.05,
    subsample=0.9,
    colsample_bytree=0.9,
    eval_metric='logloss',
    scale_pos_weight=(y_train == 0).sum() / (y_train == 1).sum(),
    random_state=42
)

xgb_model.fit(X_train, y_train)

/opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages/xgboost/core.py:377: FutureWarning: Your system has an old version of glibc (< 2.28). We will stop supporting Linux distros with glibc older than 2.28 after **May 31, 2025**. Please upgrade to a recent Linux distro (with glibc >= 2.28) to use future versions of XGBoost.
Note: You have installed the 'manylinux2014' variant of XGBoost. Certain features such as GPU algorithms or federated learning are not available. To use these features, please upgrade to a recent Linux distro with glibc 2.28+, and install the 'manylinux_2_28' variant.
  warnings.warn(

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.9, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=None,
              num_parallel_tree=None, ...)

In [48]:
roc_auc_xgb = roc_auc_score(
    y_test,
    xgb_model.predict_proba(X_test)[:, 1]
)

precision, recall, _ = precision_recall_curve(
    y_test,
    xgb_model.predict_proba(X_test)[:, 1]
)
pr_auc_xgb = auc(recall, precision)

comparison = pd.DataFrame({
    'Model': ['Logistic Regression', 'XGBoost'],
    'ROC_AUC': [roc_auc_log, roc_auc_xgb],
    'PR_AUC': [pr_auc_log, pr_auc_xgb]
})

comparison

                 Model   ROC_AUC    PR_AUC
0  Logistic Regression  0.818396  0.613376
1              XGBoost  0.812037  0.593304

In [49]:
coef_table = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': log_model.coef_[0]
}).sort_values(by='Coefficient', ascending=False)

coef_table

               Feature  Coefficient
5             is_fiber     1.193428
6      is_new_customer     0.341771
4        service_count     0.114887
1    charge_per_tenure     0.052025
0         tenure_years    -0.089057
3             auto_pay    -0.295407
2  contract_commitment    -1.085418

In [50]:
importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': xgb_model.feature_importances_
}).sort_values(by='Importance', ascending=False)

importance

               Feature  Importance
2  contract_commitment    0.595741
5             is_fiber    0.221560
1    charge_per_tenure    0.063838
3             auto_pay    0.040406
0         tenure_years    0.039457
4        service_count    0.030663
6      is_new_customer    0.008334

In [51]:
df['churn_probability'] = xgb_model.predict_proba(X)[:, 1]

In [52]:
# Target top 10% highest risk customers
threshold = df['churn_probability'].quantile(0.90)

df['target_flag'] = (df['churn_probability'] >= threshold).astype(int)

# Recall captured
recall_at_10 = (
    df[df['target_flag'] == 1]['Churn']
    .eq('Yes')
    .mean()
)

recall_at_10

np.float64(0.765625)

In [53]:
baseline_churn = (df['Churn'] == 'Yes').mean()

lift_10 = recall_at_10 / baseline_churn
lift_10

np.float64(2.88061797752809)

In [54]:
# Hypothetical assumptions
avg_monthly_revenue = df['MonthlyCharges'].mean()
retention_success_rate = 0.30  # 30% churn reduction
months_saved = 6

saved_revenue = (
    df[df['target_flag'] == 1].shape[0] *
    recall_at_10 *
    retention_success_rate *
    avg_monthly_revenue *
    months_saved
)

saved_revenue

np.float64(62867.22158703071)

### ***Targeting the top 10% highest-risk customers could capture ~3× more churners than random selection and potentially save ₹62867.22 revenue over 6 months.***